# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jim Dion
email: jamesdion4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You can do anything you want at jimdion.com!
  Thanks for visiting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jimdion.com" # the base hostname & protocol for your site

github_username:  jamesdion4

# Build settings
markdown: kramdown
